#!/usr/bin/env ruby -w

RADII = [20, 40]
POINTS_PER_CIRCLE = 6

coordinates = []
RADII.each do |radius|
  sector = 360 / POINTS_PER_CIRCLE
  POINTS_PER_CIRCLE.times do |i|
    angle = sector * i
    x = (radius * Math.cos(angle * Math::PI / 180)).round(2)
    y = (radius * Math.sin(angle * Math::PI / 180)).round(2)
    coordinates << [x, y]
  end
end

puts "G29 ="
puts "\tM561; (RFS) Reset bed matrix"

coordinates.each_with_index do |coordinate, i|
  x, y = coordinate
  puts "\tM557 P#{i} X#{x} Y#{y} Z6.0"
end

puts "\tG28 ; home steppers"

coordinates.length.times do |i|
  puts "\tG30 P#{i} S F3000"
end

puts "\tM561 U; (RFS) Update the matrix based on probe data"
puts "\tM561 S; Show the current matrix"
puts "\tM500; (RFS) Save data"

